# Generated by Django 4.2.30 on 2026-08-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_store_order_user_id_c9744e_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalizationrequest',
            name='ai_prompt',
        ),
        migrations.RemoveField(
            model_name='personalizationrequest',
            name='base_image',
        ),
        migrations.RemoveField(
            model_name='personalizationrequest',
            name='scale_x',
        ),
        migrations.RemoveField(
            model_name='personalizationrequest',
            name='scale_y',
        ),
        migrations.AlterField(
            model_name='personalizationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('admin_approved', 'Admin Approved'), ('order_accepted', 'Order Accepted'), ('rejected', 'Rejected')], default='pending', max_length=15),
        ),
    ]
