# Generated by Django 4.2.30 on 2026-08-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_personalizationrequest_ai_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_buy_url',
            field=models.URLField(blank=True, help_text='External platform URL to redirect for purchase', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='external_platform_name',
            field=models.CharField(blank=True, help_text='Platform name shown on button, e.g. Amazon, Flipkart', max_length=100, null=True),
        ),
    ]
