# Generated by Django 4.2.30 on 2026-08-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_external_buy_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_line1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_line2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address_line1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address_line2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
