# Generated by Django 4.2.30 on 2026-09-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_address_line1_alter_order_address_line2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizationrequest',
            name='product',
        ),
        migrations.RemoveField(
            model_name='customizationrequest',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='cart',
            name='store_cart_user_id_3a541e_idx',
        ),
        migrations.RemoveIndex(
            model_name='cart',
            name='store_cart_session_e2cd27_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='store_carti_cart_id_8cee36_idx',
        ),
        migrations.RemoveIndex(
            model_name='personalizationrequest',
            name='store_perso_status_290926_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='store_produ_categor_6683b7_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='store_produ_can_cus_45b499_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, help_text='Estimated delivery date shown at checkout', null=True),
        ),
        migrations.DeleteModel(
            name='CustomizationRequest',
        ),
    ]
